# Generated by Django 4.2 on 2023-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieArmoire',
            fields=[
                ('id_anomalie_cm', models.IntegerField(db_column='ID_Anomalie_CM', primary_key=True, serialize=False)),
                ('date_heure_visite', models.DateTimeField(blank=True, db_column='Date_heure_visite', null=True)),
                ('opÚrateur', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Opérateur', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type', max_length=50, null=True)),
                ('commentaire', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Commentaire', max_length=300, null=True)),
                ('image', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image', max_length=100, null=True)),
                ('etat', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etat', max_length=50, null=True)),
                ('etat1', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etat1', max_length=50, null=True)),
                ('ponctuation', models.IntegerField(blank=True, db_column='Ponctuation', null=True)),
            ],
            options={
                'db_table': 'Anomalie_Armoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnomaliePl',
            fields=[
                ('id_anomalie_pl', models.IntegerField(db_column='ID_Anomalie_PL', primary_key=True, serialize=False)),
                ('date_heure_visite', models.DateTimeField(blank=True, db_column='Date_heure_visite', null=True)),
                ('opÚrateur', models.CharField(blank=True, db_collation='French_CI_AS', db_column='OpÚrateur', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type', max_length=50, null=True)),
                ('commentaire', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Commentaire', max_length=200, null=True)),
                ('image', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('options', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Options', max_length=50, null=True)),
                ('etat', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etat', max_length=50, null=True)),
                ('ponctuation', models.IntegerField(blank=True, db_column='Ponctuation', null=True)),
            ],
            options={
                'db_table': 'Anomalie_PL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Armoire',
            fields=[
                ('code_armoire', models.CharField(db_collation='French_CI_AS', db_column='Code_Armoire', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Description', max_length=50, null=True)),
                ('designation_poste', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Designation_Poste', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=10, max_digits=11, null=True)),
                ('x_geomÚtrie', models.CharField(blank=True, db_collation='French_CI_AS', db_column='X_GeomÚtrie', max_length=100, null=True)),
                ('numero_compteur', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Numero_Compteur', max_length=50, null=True)),
                ('implantation_compteur', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Implantation_Compteur', max_length=50, null=True)),
                ('hierarchie', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Hierarchie', max_length=50, null=True)),
                ('mode_pose', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Mode_Pose', max_length=50, null=True)),
                ('type_alimentation', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Alimentation', max_length=50, null=True)),
                ('section_arrivee', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Section_Arrivee', max_length=50, null=True)),
                ('nombre_departs', models.IntegerField(blank=True, db_column='Nombre_Departs', null=True)),
                ('type_protection', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Protection', max_length=50, null=True)),
                ('calibre_protection', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Calibre_Protection', max_length=50, null=True)),
                ('mode_allumage', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Mode_Allumage', max_length=50, null=True)),
                ('telegestion', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Telegestion', max_length=3, null=True)),
                ('ip', models.CharField(blank=True, db_collation='French_CI_AS', db_column='IP', max_length=50, null=True)),
                ('mise_terre', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Mise_Terre', max_length=50, null=True)),
                ('resistance_terre', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Resistance_Terre', max_length=50, null=True)),
                ('type_manoeuvre', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Manoeuvre', max_length=50, null=True)),
                ('hauteur', models.FloatField(blank=True, db_column='Hauteur', null=True)),
                ('largeur', models.FloatField(blank=True, db_column='Largeur', null=True)),
                ('profondeur', models.FloatField(blank=True, db_column='Profondeur', null=True)),
                ('etat', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etat', max_length=50, null=True)),
                ('image1', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image1', max_length=100, null=True)),
                ('image2', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image2', max_length=100, null=True)),
                ('image3', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image3', max_length=100, null=True)),
                ('image4', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image4', max_length=100, null=True)),
                ('image5', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image5', max_length=100, null=True)),
                ('image6', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image6', max_length=100, null=True)),
                ('image7', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image7', max_length=100, null=True)),
                ('image8', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Image8', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Armoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('code_district', models.CharField(db_collation='French_CI_AS', db_column='Code_District', max_length=50, primary_key=True, serialize=False)),
                ('nom_district', models.CharField(db_collation='French_CI_AS', db_column='Nom_District', max_length=50)),
            ],
            options={
                'db_table': 'Arrondissement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('code_axe', models.CharField(db_collation='French_CI_AS', db_column='Code_Axe', max_length=50, primary_key=True, serialize=False)),
                ('nom_axe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_Axe', max_length=100, null=True)),
                ('type_axe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Axe', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Axe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id_depart', models.CharField(db_collation='French_CI_AS', db_column='ID_Depart', max_length=50, primary_key=True, serialize=False)),
                ('nom_depart', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_Depart', max_length=50, null=True)),
                ('type_depart', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Depart', max_length=50, null=True)),
                ('type_protection', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Protection', max_length=50, null=True)),
                ('calibre', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Calibre', max_length=50, null=True)),
                ('tension', models.FloatField(blank=True, db_column='Tension', null=True)),
                ('type_cable', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Cable', max_length=50, null=True)),
                ('section_cable', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Section_Cable', max_length=50, null=True)),
                ('cheminement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Cheminement', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Depart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Luminaire',
            fields=[
                ('id_luminaire', models.CharField(db_collation='French_CI_AS', db_column='ID_Luminaire', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Description', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Luminaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleLuminaire',
            fields=[
                ('id_modele_luminaire', models.IntegerField(db_column='ID_Modele_luminaire', primary_key=True, serialize=False)),
                ('nom_modele_luminaire', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_modele_luminaire', max_length=50, null=True)),
                ('alias1', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Alias1', max_length=100, null=True)),
                ('alias2', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Alias2', max_length=100, null=True)),
                ('type_luminaire', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_luminaire', max_length=50, null=True)),
                ('hauteur', models.FloatField(blank=True, db_column='Hauteur', null=True)),
                ('marque', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Marque', max_length=50, null=True)),
                ('nom_commercial', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_commercial', max_length=50, null=True)),
                ('puissance_lampe', models.FloatField(blank=True, db_column='Puissance_lampe', null=True)),
                ('puissance_equipement', models.FloatField(blank=True, db_column='Puissance_equipement', null=True)),
                ('tension', models.FloatField(blank=True, db_column='Tension', null=True)),
                ('type_lampe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_lampe', max_length=50, null=True)),
                ('tempÚrature_couleur', models.FloatField(blank=True, db_column='TempÚrature_couleur', null=True)),
                ('type_Úquipement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Úquipement', max_length=50, null=True)),
                ('reference_equipement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Reference_equipement', max_length=50, null=True)),
                ('type_vasque', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_vasque', max_length=50, null=True)),
                ('protection_surintensites', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Protection_surintensites', max_length=50, null=True)),
                ('optique_luminaire', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Optique_luminaire', max_length=50, null=True)),
                ('inclinaison', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Inclinaison', max_length=50, null=True)),
                ('type_cable', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_cable', max_length=50, null=True)),
                ('section_cable', models.FloatField(blank=True, db_column='Section_cable', null=True)),
                ('type_raccordement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_raccordement', max_length=50, null=True)),
                ('image1', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('reflecteur', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Reflecteur', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Modele_luminaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleSupport',
            fields=[
                ('id_modele_support', models.IntegerField(db_column='ID_modele_support', primary_key=True, serialize=False)),
                ('nom_modele_support', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_modele_support', max_length=10, null=True)),
                ('alias', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Alias', max_length=100, null=True)),
                ('type_eclairage', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_Eclairage', max_length=50, null=True)),
                ('type_support', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_support', max_length=50, null=True)),
                ('type_ancrage', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_ancrage', max_length=50, null=True)),
                ('matÚriau_support', models.CharField(blank=True, db_collation='French_CI_AS', db_column='MatÚriau_support', max_length=50, null=True)),
                ('nom_commercial', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom_commercial', max_length=50, null=True)),
                ('hauteur_support', models.FloatField(blank=True, db_column='Hauteur_support', null=True)),
                ('nb_luminaire_par_sup', models.IntegerField(blank=True, db_column='Nb_luminaire_par_sup', null=True)),
                ('avancÚe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='AvancÚe', max_length=50, null=True)),
                ('image', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('plan_dessin', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Plan_dessin', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Modele_support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id_support', models.CharField(db_collation='French_CI_AS', db_column='ID_support', max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=10, max_digits=11, null=True)),
                ('etat_general', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etat_general', max_length=50, null=True)),
                ('section_cable', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Section_cable', max_length=50, null=True)),
                ('image1', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('image2', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('image3', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('image4', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('type_cable_alimentation', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_cable_alimentation', max_length=50, null=True)),
                ('type_raccordement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Type_raccordement', max_length=50, null=True)),
                ('protection_surintensites', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Protection_surintensites', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('code_ville', models.CharField(db_collation='French_CI_AS', db_column='Code_Ville', max_length=3, primary_key=True, serialize=False)),
                ('nom_ville', models.CharField(db_collation='French_CI_AS', db_column='Nom_Ville', max_length=50)),
            ],
            options={
                'db_table': 'Ville',
                'managed': False,
            },
        ),
    ]
